'1': '&5Location:'
'2': '&7%player_location%'
'3': ''
'4': '&5Player Info:'
'5': '&eKills: %player_kills%'
'6': '&eDeaths: %player_deaths%'
'7': ''
'8': '&5Online Players:'
'9': '&e%online_players%'
'10': ''
'11': ''
'12': ''
'13': '&e/coords'
'14': '&e/request'
'15': '&e/lives'
'16': ''
'17': ''
'18': ''
'19': ''
'20': '&7&m---------------'
'21': '&6&lSaifed.Me'
'22': ''
'23': ''
'24': ''
'25': ''
'26': ''
'27': ''
'28': ''
'29': ''
'30': ''
'31': '&5 Useful Commands'
'32': ''
'33': '&e/help'
'34': '&e/report'
'35': '&e/pvp'
'36': ''
'37': ''
'38': ''
'39': ''
'40': '&7&m---------------'
'41': '&5End Portal:'
'42': '&e450, 450'
'43': ''
'44': '&5Map Kit:'
'45': '&eS1, P1'
'46': ''
'47': '&5Sotw was:'
'48': '&e10/10/2016'
'49': ''
'50': ''
'51': ''
'52': ''
'53': '&e/factions'
'54': '&e/focus'
'55': '&e/mapkit'
'56': ''
'57': ''
'58': ''
'59': ''
'60': '&7&m---------------'